### ISSUE TITLE
uncaught dup key with caracal @ develop

### ISSUE THREAD

**Issue by birm** [camicroscope/Caracal#140]
```
ca-back   | MongoError: E11000 duplicate key error collection: camic.configuration index: config_name_1 dup key: { config_name: "additional_links" }
ca-back   |     at MessageStream.messageHandler (/src/node_modules/mongodb/lib/cmap/connection.js:268:20)
ca-back   |     at MessageStream.emit (node:events:394:28)
ca-back   |     at processIncomingData (/src/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
ca-back   |     at MessageStream._write (/src/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
ca-back   |     at writeOrBuffer (node:internal/streams/writable:389:12)
ca-back   |     at _write (node:internal/streams/writable:330:10)
ca-back   |     at MessageStream.Writable.write (node:internal/streams/writable:334:10)
ca-back   |     at Socket.ondata (node:internal/streams/readable:749:22)
ca-back   |     at Socket.emit (node:events:394:28)
ca-back   |     at addChunk (node:internal/streams/readable:312:12) {
ca-back   |   ok: 0,
ca-back   |   code: 11000,
ca-back   |   codeName: 'DuplicateKey',
ca-back   |   keyPattern: { config_name: 1 },
ca-back   |   keyValue: { config_name: 'additional_links' }
ca-back   | }
```

**Comment by AbhishekPanta8** [comment]
This error is occurring because there is already a document in the MongoDB collection with a value of 'additional_links' in the config_name field, and another attempt is being made to insert a document with the same value in the config_name field.

Can you please assign this to me?

**Comment by birm** [comment]
Submit a PR if you have a fix

**Comment by AbhishekPanta8** [comment]
PR should be raised to master or develop?

**Comment by AbhishekPanta8** [comment]
$ git push -u origin dupKeyFix
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

When I am trying to push the code then it is showing this error.
Can you please help me out? What do I need to do?
