### ISSUE TITLE
Add timestamps to stdout logs

### ISSUE THREAD

**Issue by birm** [camicroscope/Caracal#160]
Right now, we just see messages, e.g. 
```
TokenExpiredError: jwt expired
    at /src/node_modules/jsonwebtoken/verify.js:190:21
    at getSecret (/src/node_modules/jsonwebtoken/verify.js:97:14)
    at module.exports [as verify] (/src/node_modules/jsonwebtoken/verify.js:101:10)
    at /src/handlers/authHandlers.js:194:11
    at Layer.handle [as handle_request] (/src/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/src/node_modules/express/lib/router/index.js:328:13)
    at /src/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/src/node_modules/express/lib/router/index.js:346:12)
    at next (/src/node_modules/express/lib/router/index.js:280:10)
    at SendStream.error (/src/node_modules/serve-static/index.js:121:7) {
  expiredAt: 2023-07-22T15:05:25.000Z
}
```

We should include a timestamp of the request itself!

**Comment by Negasi-Kifle** [comment]
Hello @birm could the following style be good enough:

```
JsonWebTokenError: jwt malformed 2024-03-27T04:40:35.824Z
JsonWebTokenError: jwt malformed
    at module.exports [as verify] (D:\Personal\outreachy\camicroscope\Caracal\node_modules\jsonwebtoken\verify.js:70:17)
    at D:\Personal\outreachy\camicroscope\Caracal\handlers\authHandlers.js:230:11
    at Layer.handle [as handle_request] (D:\Personal\outreachy\camicroscope\Caracal\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (D:\Personal\outreachy\camicroscope\Caracal\node_modules\express\lib\router\index.js:328:13)       
    at D:\Personal\outreachy\camicroscope\Caracal\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (D:\Personal\outreachy\camicroscope\Caracal\node_modules\express\lib\router\index.js:346:12)
    at next (D:\Personal\outreachy\camicroscope\Caracal\node_modules\express\lib\router\index.js:280:10)
    at SendStream.error (D:\Personal\outreachy\camicroscope\Caracal\node_modules\serve-static\index.js:121:7)
    at SendStream.emit (node:events:513:28)
    at SendStream.error (D:\Personal\outreachy\camicroscope\Caracal\node_modules\send\index.js:270:17)
```
