### ISSUE TITLE
Login/check breaks

### ISSUE THREAD

**Issue by birm** [camicroscope/Caracal#41]
ca-back     | (node:432) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
ca-back     | /root/src/node_modules/mongodb/lib/topologies/server.js:301
ca-back     |           throw err;
ca-back     |           ^
ca-back     | 
ca-back     | TypeError: Cannot read property '_id' of undefined
ca-back     |     at /root/src/handlers/dataHandlers.js:14:20
ca-back     |     at /root/src/node_modules/mongodb/lib/operations/execute_operation.js:75:17
ca-back     |     at executeCallback (/root/src/node_modules/mongodb/lib/operations/execute_operation.js:68:9)
ca-back     |     at /root/src/node_modules/mongodb/lib/operations/connect.js:195:7
ca-back     |     at connectCallback (/root/src/node_modules/mongodb/lib/operations/connect.js:345:5)
ca-back     |     at /root/src/node_modules/mongodb/lib/operations/connect.js:438:5
ca-back     |     at Server.connectHandler (/root/src/node_modules/mongodb/lib/topologies/server.js:298:9)
ca-back     |     at Object.onceWrapper (events.js:417:26)
ca-back     |     at Server.emit (events.js:310:20)
ca-back     |     at Pool.<anonymous> (/root/src/node_modules/mongodb/lib/core/topologies/server.js:379:12)
ca-back     | listening on 4010

**Comment by birm** [comment]
a small oversight, so an easy fix via a5f83e2576b9a6b3c2f36069eac5d92917233961
