### ISSUE TITLE
Segmentations break

### ISSUE THREAD

**Issue by birm** [camicroscope/Caracal#42]
Open a slide with segmentations; viewing the segmentations fails. 
logs for caracal say 
```
/root/src/node_modules/mongodb/lib/utils.js:133
      throw err;
      ^
TypeError: Cannot read property 'forEach' of null
    at /root/src/handlers/dataHandlers.js:23:20
    at /root/src/node_modules/mongodb/lib/operations/execute_operation.js:76:14
    at executeCallback (/root/src/node_modules/mongodb/lib/operations/execute_operation.js:67:25)
    at handleCallback (/root/src/node_modules/mongodb/lib/utils.js:129:55)
    at /root/src/node_modules/mongodb/lib/operations/to_array.js:30:40
    at ClientSession.endSession (/root/src/node_modules/mongodb/lib/core/sessions.js:135:41)
    at Cursor._endSession (/root/src/node_modules/mongodb/lib/core/cursor.js:399:15)
    at /root/src/node_modules/mongodb/lib/operations/to_array.js:30:22
    at /root/src/node_modules/mongodb/lib/core/cursor.js:750:9
    at done (/root/src/node_modules/mongodb/lib/core/cursor.js:463:7)
```

**Comment by birm** [comment]
https://github.com/camicroscope/caMicroscope/commit/e6ff5a9269e8960ef7c9141774998ff78d4175a8 fixes a related issue, but likely not the whole issue.

**Comment by birm** [comment]
fixed with https://github.com/camicroscope/Caracal/commit/462937f19e6d137e2142584ef9be194afbeab0b3
